### ISSUE TITLE
Navbar zůstává v angličtině

### ISSUE THREAD

**Issue by DooMxDD** [PavelTajdus/ProcessWire-Czech-Language-Pack#4]
Zdravím, nepřekládají se mi texty v hlavní navigaci na UIKit 0.3.0, včetně dropdowns. Zbytek se překládá v pořádku.
Používám poslední master verzi PW: 3.0.123

Nějaký nápad jak to vyřešit?

Díky :)

**Comment by PavelTajdus** [comment]
I po odhlášení a přihlášení? Tohle se mi stává když se neodhlásím. Pak už je vše ok.

**Comment by DooMxDD** [comment]
> I po odhlášení a přihlášení? Tohle se mi stává když se neodhlásím. Pak už je vše ok.

Pomohlo, děkuji moc za bleskurychlou reakci. :)
